# Sandbox 

## isc 2 working with data in python

### date Wednesday 2023.11.15 

In [3]:
import numpy as np

In [4]:
rng = np.random.default_rng()
rng

Generator(PCG64) at 0x7F353EC58D60

In [5]:
hjk = rng.integers(low=0, high=12, size=12).reshape(3,4)  

In [6]:
hjk

array([[ 9,  8,  4, 10],
       [ 1,  7, 11,  5],
       [11,  1,  3,  2]])

In [7]:
hjk.shape

(3, 4)

In [8]:
h = np.arange(1,13)

In [11]:
h.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [12]:
h.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
import numpy.ma as MA

In [16]:
masked_arr = MA.masked_array(h, mask=h>5)
masked_arr

masked_array(data=[1, 2, 3, 4, 5, --, --, --, --, --, --, --],
             mask=[False, False, False, False, False,  True,  True,  True,
                    True,  True,  True,  True],
       fill_value=999999)

In [17]:
import matplotlib.pyplot as plt

In [18]:
plt.legend

['Annotation',
 'Arrow',
 'Artist',
 'AutoLocator',
 'Axes',
 'Button',
 'Circle',
 'Figure',
 'FigureCanvasBase',
 'FixedFormatter',
 'FixedLocator',
 'FormatStrFormatter',
 'Formatter',
 'FuncFormatter',
 'GridSpec',
 'IndexLocator',
 'Line2D',
 'LinearLocator',
 'Locator',
 'LogFormatter',
 'LogFormatterExponent',
 'LogFormatterMathtext',
 'LogLocator',
 'MaxNLocator',
 'MouseButton',
 'MultipleLocator',
 'Normalize',
 'NullFormatter',
 'NullLocator',
 'Number',
 'PolarAxes',
 'Polygon',
 'Rectangle',
 'ScalarFormatter',
 'Slider',
 'Subplot',
 'SubplotSpec',
 'Text',
 'TickHelper',
 'Widget',
 '_INSTALL_FIG_OBSERVER',
 '_IP_REGISTERED',
 '_IoffContext',
 '_IonContext',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_api',
 '_auto_draw_if_interactive',
 '_backend_mod',
 '_copy_docstring_and_deprecators',
 '_get_backend_mod',
 '_get_required_interactive_framework',
 '_interactive_bk',
 '_log',
 '_pylab_helpers',
 '_

In [21]:
mydict = {'name':'Riccardo', 'lastname' : 'Monfaridni', 'age':33}

In [25]:
mydict.values()

dict_values(['Riccardo', 'Monfaridni', 33])

In [26]:
longitudes[:] = np.arange(-180, 180, 2.5)

NameError: name 'longitudes' is not defined